name: kursova
description: "Web application for choosing a road transport route."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  #DI
  get_it: ^7.6.7

  #BLoC
  flutter_bloc: ^8.1.3

  #UI
  flutter_svg: ^2.0.9
  loading_animation_widget: ^1.2.0+4
  flutter_map: ^6.1.0
  top_snackbar_flutter: ^3.1.0
  easy_localization: ^3.0.4
  dropdown_button2: ^2.3.9
  country_flags: ^2.2.0

  #Rest
  http: ^1.2.0
  uuid: ^4.3.3
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  latlong2: ^0.9.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.0
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/google_fonts/
    - assets/translations/

  fonts:
  - family: Inter
    fonts:
      - asset: assets/google_fonts/Inter-Black.ttf
        weight: 900
      - asset: assets/google_fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/google_fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/google_fonts/Inter-ExtraLight.ttf
        weight: 200
      - asset: assets/google_fonts/Inter-Light.ttf
        weight: 300
      - asset: assets/google_fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/google_fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/google_fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/google_fonts/Inter-Thin.ttf
        weight: 100